const fmt=(n)=>"Rp "+Math.round(n||0).toLocaleString("id-ID");
const today=()=>new Date().toISOString().slice(0,10);
const month=()=>new Date().toISOString().slice(0,7);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const store={get(k,fb){try{return JSON.parse(localStorage.getItem(k))??fb;}catch{return fb;}},set(k,v){localStorage.setItem(k,JSON.stringify(v));}};
const SEED_SISWA=[["Aisyah Putri","Bu Rina"],["Bagas Pratama","Pak Dedi"],["Citra Lestari","Bu Sari"],["Dimas Wibowo","Pak Andi"],["Eka Nurhaliza","Bu Maya"],["Farhan Malik","Pak Yusuf"],["Gita Rahma","Bu Lina"],["Hadi Santoso","Pak Budi"],["Intan Permata","Bu Dewi"],["Joko Saputra","Pak Heru"],["Kirana Ayu","Bu Nia"],["Lutfi Rahman","Pak Agus"]];
function seedIfEmpty(){if(store.get("kk_ready",false))return;const siswa=SEED_SISWA.map(([nama,ortu],i)=>({id:"s"+(i+1),nama,ortu,wa:"6281356510403",tabungan:i%3===0?50000:i%2===0?25000:10000}));const m=month();const iuran={};siswa.forEach((s,i)=>{iuran[s.id]=i<8;});const txs=[{id:uid(),date:today(),jenis:"masuk",kat:"Iuran bulanan",nom:200000,ket:"Iuran 8 siswa",keg:""},{id:uid(),date:today(),jenis:"keluar",kat:"Konsumsi",nom:45000,ket:"Snack rapat paguyuban",keg:""},{id:uid(),date:today(),jenis:"masuk",kat:"Iuran kegiatan",nom:150000,ket:"DP study tour",keg:"k1"}];store.set("kk_profil",{kelas:"Kelas 5A",sekolah:"SDN Melati",bendahara:"Bu Rina",iuran:25000});store.set("kk_siswa",siswa);store.set("kk_iuran",{[m]:{nominal:25000,status:iuran}});store.set("kk_keg",[{id:"k1",nama:"Study Tour Kebun Raya",target:1500000}]);store.set("kk_tx",txs);store.set("kk_tabtx",[]);store.set("kk_ready",true);}
const state={};
function load(){seedIfEmpty();state.profil=store.get("kk_profil",{kelas:"Kelas",sekolah:"",bendahara:"",iuran:25000});state.siswa=store.get("kk_siswa",[]);state.iuran=store.get("kk_iuran",{});state.keg=store.get("kk_keg",[]);state.tx=store.get("kk_tx",[]);state.tabtx=store.get("kk_tabtx",[]);}
function save(){store.set("kk_profil",state.profil);store.set("kk_siswa",state.siswa);store.set("kk_iuran",state.iuran);store.set("kk_keg",state.keg);store.set("kk_tx",state.tx);store.set("kk_tabtx",state.tabtx);}
function toast(msg){const t=document.querySelector("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700);}
function saldoKas(){return state.tx.reduce((s,t)=>s+(t.jenis==="masuk"?t.nom:-t.nom),0);}
function totalTabungan(){return state.siswa.reduce((s,x)=>s+(x.tabungan||0),0);}
function iuranBulan(bln){if(!state.iuran[bln])state.iuran[bln]={nominal:state.profil.iuran||25000,status:{}};return state.iuran[bln];}
function monthLabel(bln){const[y,m]=(bln||month()).split("-");const nama=["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"];return(nama[+m-1]||m)+" "+y;}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));document.querySelector("#page-"+id).classList.add("active");if(id==="beranda")renderHome();if(id==="iuran")renderIuran();if(id==="kas")renderKas();if(id==="tabung")renderTabung();if(id==="lapor")renderLapor();}
function renderHome(){const p=state.profil;document.querySelector("#kelas-nama").textContent=p.kelas+" · "+(p.sekolah||"Paguyuban");document.querySelector("#kelas-sub").textContent="Bendahara: "+(p.bendahara||"-");const bln=month();const pack=iuranBulan(bln);const lunas=state.siswa.filter(s=>pack.status[s.id]).length;const target=state.siswa.length*(pack.nominal||0);const terkumpul=lunas*(pack.nominal||0);const pct=target?Math.round(terkumpul/target*100):0;document.querySelector("#s-kas").textContent=fmt(saldoKas());document.querySelector("#s-tabung").textContent=fmt(totalTabungan());document.querySelector("#s-lunas").textContent=lunas+"/"+state.siswa.length;document.querySelector("#s-bulan").textContent=monthLabel(bln);document.querySelector("#s-tunggak").textContent=fmt((state.siswa.length-lunas)*(pack.nominal||0));document.querySelector("#s-iuran").textContent=fmt(terkumpul)+" / "+fmt(target);document.querySelector("#s-bar").style.width=pct+"%";document.querySelector("#s-pct").textContent=pct+"% iuran bulan ini masuk";const recent=[...state.tx].sort((a,b)=>(b.date+b.id).localeCompare(a.date+a.id)).slice(0,6);document.querySelector("#recent").innerHTML=recent.length?recent.map(txHtml).join(""):'<div class="empty">Belum ada mutasi.</div>';}
function txHtml(t){const sign=t.jenis==="masuk"?"+":"-";const cls=t.jenis==="masuk"?"in":"out";return '<div class="item"><div><strong>'+t.kat+'</strong><div class="meta">'+t.date+" · "+(t.ket||"-")+'</div></div><strong class="'+cls+'">'+sign+" "+fmt(t.nom)+"</strong></div>";}
function renderIuran(){const elB=document.querySelector("#i-bulan");if(elB&&!elB.value)elB.value=month();const bln=elB.value||month();const pack=iuranBulan(bln);document.querySelector("#i-nominal").value=pack.nominal;document.querySelector("#iuran-list").innerHTML=state.siswa.map(s=>{const ok=!!pack.status[s.id];return '<div class="siswa"><div><strong>'+s.nama+'</strong><div class="meta">'+s.ortu+'</div></div><div><span class="badge '+(ok?"ok":"no")+'">'+(ok?"Lunas":"Belum")+'</span> <button class="btn btn-ghost btn-sm" onclick="toggleIuran(\''+s.id+'\')">'+(ok?"Batal":"Bayar")+"</button></div></div>";}).join("")||'<div class="empty">Tambah siswa di tab Laporan.</div>';}
function toggleIuran(id){const bln=document.querySelector("#i-bulan").value||month();const pack=iuranBulan(bln);const now=!pack.status[id];pack.status[id]=now;if(now){const s=state.siswa.find(x=>x.id===id);state.tx.push({id:uid(),date:today(),jenis:"masuk",kat:"Iuran bulanan",nom:pack.nominal,ket:(s?s.nama:id)+" · "+monthLabel(bln),keg:""});}save();renderIuran();toast(now?"Iuran dicatat":"Status diubah");}
function setIuran(){const bln=document.querySelector("#i-bulan").value||month();const pack=iuranBulan(bln);pack.nominal=Number(document.querySelector("#i-nominal").value)||0;state.profil.iuran=pack.nominal;save();toast("Tarif iuran disimpan");}
let jenisKas="masuk";
function renderKas(){document.querySelector("#k-date").value=today();const sel=document.querySelector("#k-keg");sel.innerHTML='<option value="">— Umum kas kelas —</option>'+state.keg.map(k=>'<option value="'+k.id+'">'+k.nama+"</option>").join("");document.querySelector("#keg-list").innerHTML=state.keg.map(k=>{const masuk=state.tx.filter(t=>t.keg===k.id&&t.jenis==="masuk").reduce((s,t)=>s+t.nom,0);const keluar=state.tx.filter(t=>t.keg===k.id&&t.jenis==="keluar").reduce((s,t)=>s+t.nom,0);const pct=k.target?Math.min(100,Math.round(masuk/k.target*100)):0;return '<div class="item"><div><strong>'+k.nama+'</strong><div class="meta">Terkumpul '+fmt(masuk)+" / "+fmt(k.target)+" · pakai "+fmt(keluar)+'</div><div class="progress"><span style="width:'+pct+'%"></span></div></div></div>';}).join("")||'<div class="empty">Belum ada kegiatan.</div>';const list=[...state.tx].sort((a,b)=>(b.date+b.id).localeCompare(a.date+a.id));document.querySelector("#kas-list").innerHTML=list.length?list.map(txHtml).join(""):'<div class="empty">Belum ada buku kas.</div>';}
function addKas(e){e.preventDefault();const nom=Number(document.querySelector("#k-nom").value)||0;if(!nom)return toast("Isi nominal");state.tx.push({id:uid(),date:document.querySelector("#k-date").value||today(),jenis:jenisKas,kat:document.querySelector("#k-kat").value,nom,ket:document.querySelector("#k-ket").value.trim(),keg:document.querySelector("#k-keg").value});save();e.target.reset();document.querySelector("#k-date").value=today();renderKas();toast("Mutasi tersimpan");}
function addKeg(){const nama=document.querySelector("#g-nama").value.trim();if(!nama)return toast("Isi nama kegiatan");state.keg.push({id:uid(),nama,target:Number(document.querySelector("#g-target").value)||0});document.querySelector("#g-nama").value="";document.querySelector("#g-target").value="";save();renderKas();toast("Kegiatan ditambah");}
function renderTabung(){const sel=document.querySelector("#t-siswa");sel.innerHTML=state.siswa.map(s=>'<option value="'+s.id+'">'+s.nama+" · "+fmt(s.tabungan||0)+"</option>").join("");const list=[...state.siswa].sort((a,b)=>(b.tabungan||0)-(a.tabungan||0));document.querySelector("#tabung-list").innerHTML=list.map(s=>'<div class="siswa"><div><strong>'+s.nama+'</strong><div class="meta">'+s.ortu+'</div></div><strong class="green">'+fmt(s.tabungan||0)+"</strong></div>").join("")||'<div class="empty">Belum ada siswa.</div>';}
function addTabung(e){e.preventDefault();const id=document.querySelector("#t-siswa").value;const s=state.siswa.find(x=>x.id===id);const nom=Number(document.querySelector("#t-nom").value)||0;const jenis=document.querySelector("#t-jenis").value;if(!s||!nom)return toast("Pilih siswa dan nominal");if(jenis==="tarik"&&(s.tabungan||0)<nom)return toast("Saldo tabungan kurang");s.tabungan=(s.tabungan||0)+(jenis==="setor"?nom:-nom);state.tabtx.push({id:uid(),date:today(),siswa:s.nama,jenis,nom,ket:document.querySelector("#t-ket").value.trim()});save();e.target.reset();renderTabung();toast("Tabungan diperbarui");}
function renderLapor(){const masuk=state.tx.filter(t=>t.jenis==="masuk").reduce((s,t)=>s+t.nom,0);const keluar=state.tx.filter(t=>t.jenis==="keluar").reduce((s,t)=>s+t.nom,0);document.querySelector("#l-kas").textContent=fmt(saldoKas());document.querySelector("#l-tab").textContent=fmt(totalTabungan());document.querySelector("#l-in").textContent=fmt(masuk);document.querySelector("#l-out").textContent=fmt(keluar);document.querySelector("#p-kelas").value=state.profil.kelas||"";document.querySelector("#p-sekolah").value=state.profil.sekolah||"";document.querySelector("#p-bendahara").value=state.profil.bendahara||"";document.querySelector("#p-iuran").value=state.profil.iuran||25000;document.querySelector("#anggota-list").innerHTML=state.siswa.map(s=>'<div class="siswa"><div><strong>'+s.nama+'</strong><div class="meta">'+s.ortu+" · "+(s.wa||"-")+'</div></div><button class="btn btn-ghost btn-sm" onclick="hapusSiswa(\''+s.id+'\')">Hapus</button></div>').join("");}
function saveProfil(){state.profil.kelas=document.querySelector("#p-kelas").value.trim()||"Kelas";state.profil.sekolah=document.querySelector("#p-sekolah").value.trim();state.profil.bendahara=document.querySelector("#p-bendahara").value.trim();state.profil.iuran=Number(document.querySelector("#p-iuran").value)||0;save();toast("Profil kelas disimpan");renderHome();}
function addSiswa(e){e.preventDefault();const nama=document.querySelector("#a-nama").value.trim();if(!nama)return toast("Isi nama siswa");state.siswa.push({id:uid(),nama,ortu:document.querySelector("#a-ortu").value.trim()||"-",wa:document.querySelector("#a-wa").value.trim(),tabungan:0});save();e.target.reset();renderLapor();toast("Siswa ditambah");}
function hapusSiswa(id){state.siswa=state.siswa.filter(s=>s.id!==id);save();renderLapor();toast("Siswa dihapus");}
function waLapor(){const p=state.profil;const bln=month();const pack=iuranBulan(bln);const lunas=state.siswa.filter(s=>pack.status[s.id]).length;const masuk=state.tx.filter(t=>t.jenis==="masuk").reduce((s,t)=>s+t.nom,0);const keluar=state.tx.filter(t=>t.jenis==="keluar").reduce((s,t)=>s+t.nom,0);const text=["*LAPORAN KAS KELAS*",p.kelas+" · "+(p.sekolah||""),"Bendahara: "+(p.bendahara||"-"),"","Saldo kas: "+fmt(saldoKas()),"Tabungan siswa: "+fmt(totalTabungan()),"Pemasukan: "+fmt(masuk),"Pengeluaran: "+fmt(keluar),"Iuran "+monthLabel(bln)+": "+lunas+"/"+state.siswa.length+" lunas","","Laporan transparan paguyuban."].join("%0A");location.href="https://wa.me/?text="+text;}
window.toggleIuran=toggleIuran;window.hapusSiswa=hapusSiswa;
document.addEventListener("DOMContentLoaded",()=>{load();document.querySelectorAll(".nav button").forEach(b=>b.addEventListener("click",()=>showPage(b.dataset.page)));document.querySelector("#btn-set-iuran").addEventListener("click",setIuran);document.querySelector("#i-bulan").addEventListener("change",renderIuran);document.querySelector("#form-kas").addEventListener("submit",addKas);document.querySelector("#btn-add-keg").addEventListener("click",addKeg);document.querySelector("#form-tabung").addEventListener("submit",addTabung);document.querySelector("#btn-save-profil").addEventListener("click",saveProfil);document.querySelector("#form-siswa").addEventListener("submit",addSiswa);document.querySelector("#btn-wa-lapor").addEventListener("click",waLapor);document.querySelectorAll(".tabs button").forEach(b=>b.addEventListener("click",()=>{jenisKas=b.dataset.jenis;document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("on",x===b));}));renderHome();});
